# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Projects/Pipeline/rez-packages/third/github.com/yamahigashi/ymtshiftercomponents/0.2.0/mgear_shifter_components/python/ymt_components/ymt_face_eyebrow_01/settingsUI.ui',
# licensing of 'D:/Projects/Pipeline/rez-packages/third/github.com/yamahigashi/ymtshiftercomponents/0.2.0/mgear_shifter_components/python/ymt_components/ymt_face_eyebrow_01/settingsUI.ui' applies.
#
# Created: Mon Jul 10 23:39:26 2023
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(419, 555)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.isSlidingSurface = QtWidgets.QCheckBox(self.groupBox_3)
        self.isSlidingSurface.setChecked(True)
        self.isSlidingSurface.setTristate(False)
        self.isSlidingSurface.setObjectName("isSlidingSurface")
        self.gridLayout_4.addWidget(self.isSlidingSurface, 0, 0, 1, 1)
        self.surfaceReference_groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.surfaceReference_groupBox.setEnabled(True)
        self.surfaceReference_groupBox.setTitle("")
        self.surfaceReference_groupBox.setFlat(False)
        self.surfaceReference_groupBox.setObjectName("surfaceReference_groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.surfaceReference_groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.surfaceReference_horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.surfaceReference_horizontalLayout_4.setObjectName("surfaceReference_horizontalLayout_4")
        self.surfaceReference_verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.surfaceReference_verticalLayout_7.setObjectName("surfaceReference_verticalLayout_7")
        self.surfaceReference_listWidget = QtWidgets.QListWidget(self.surfaceReference_groupBox)
        self.surfaceReference_listWidget.setAutoScroll(False)
        self.surfaceReference_listWidget.setProperty("showDropIndicator", False)
        self.surfaceReference_listWidget.setDragDropOverwriteMode(False)
        self.surfaceReference_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.surfaceReference_listWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.surfaceReference_listWidget.setAlternatingRowColors(True)
        self.surfaceReference_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.surfaceReference_listWidget.setGridSize(QtCore.QSize(0, 0))
        self.surfaceReference_listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.surfaceReference_listWidget.setSelectionRectVisible(False)
        self.surfaceReference_listWidget.setObjectName("surfaceReference_listWidget")
        self.surfaceReference_verticalLayout_7.addWidget(self.surfaceReference_listWidget)
        self.surfaceReference_horizontalLayout_4.addLayout(self.surfaceReference_verticalLayout_7)
        self.surfaceReference_verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.surfaceReference_verticalLayout_8.setSpacing(3)
        self.surfaceReference_verticalLayout_8.setObjectName("surfaceReference_verticalLayout_8")
        self.surfaceReferenceAdd_pushButton_4 = QtWidgets.QPushButton(self.surfaceReference_groupBox)
        self.surfaceReferenceAdd_pushButton_4.setObjectName("surfaceReferenceAdd_pushButton_4")
        self.surfaceReference_verticalLayout_8.addWidget(self.surfaceReferenceAdd_pushButton_4)
        self.surfaceReferenceRemove_pushButton_4 = QtWidgets.QPushButton(self.surfaceReference_groupBox)
        self.surfaceReferenceRemove_pushButton_4.setObjectName("surfaceReferenceRemove_pushButton_4")
        self.surfaceReference_verticalLayout_8.addWidget(self.surfaceReferenceRemove_pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.surfaceReference_verticalLayout_8.addItem(spacerItem)
        self.surfaceReference_horizontalLayout_4.addLayout(self.surfaceReference_verticalLayout_8)
        self.gridLayout_7.addLayout(self.surfaceReference_horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.surfaceReference_groupBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.overrideNegate_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.overrideNegate_checkBox.setText("Override Negate Axis Direction For \"R\" Side")
        self.overrideNegate_checkBox.setObjectName("overrideNegate_checkBox")
        self.verticalLayout_3.addWidget(self.overrideNegate_checkBox)
        self.addJoints_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.addJoints_checkBox.setText("Add Joints")
        self.addJoints_checkBox.setChecked(True)
        self.addJoints_checkBox.setObjectName("addJoints_checkBox")
        self.verticalLayout_3.addWidget(self.addJoints_checkBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        self.surfaceReference_listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Form", "Surface", None, -1))
        self.isSlidingSurface.setText(QtWidgets.QApplication.translate("Form", "Sliding on Surface", None, -1))
        self.surfaceReferenceAdd_pushButton_4.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.surfaceReferenceRemove_pushButton_4.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "GroupBox", None, -1))

