# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/matsumoto/projects/gdl/svn/trunk/maya/maya_modules/red/python/ymt_component/ymt_shoulder_01/settingsUI.ui'
#
# Created: Wed Feb 22 20:05:08 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(269, 559)
        self.upvRefArray_groupBox = QtWidgets.QGroupBox(Form)
        self.upvRefArray_groupBox.setGeometry(QtCore.QRect(10, 10, 249, 176))
        self.upvRefArray_groupBox.setObjectName("upvRefArray_groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.upvRefArray_groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 231, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.upvRefArray_horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.upvRefArray_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.upvRefArray_horizontalLayout.setObjectName("upvRefArray_horizontalLayout")
        self.upvRefArray_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.upvRefArray_verticalLayout_1.setObjectName("upvRefArray_verticalLayout_1")
        self.refArray_listWidget = QtWidgets.QListWidget(self.layoutWidget_2)
        self.refArray_listWidget.setDragDropOverwriteMode(True)
        self.refArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.refArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.refArray_listWidget.setAlternatingRowColors(True)
        self.refArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.refArray_listWidget.setSelectionRectVisible(False)
        self.refArray_listWidget.setObjectName("refArray_listWidget")
        self.upvRefArray_verticalLayout_1.addWidget(self.refArray_listWidget)
        self.upvRefArray_horizontalLayout.addLayout(self.upvRefArray_verticalLayout_1)
        self.upvRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.upvRefArray_verticalLayout_2.setObjectName("upvRefArray_verticalLayout_2")
        self.refArrayAdd_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.refArrayAdd_pushButton.setObjectName("refArrayAdd_pushButton")
        self.upvRefArray_verticalLayout_2.addWidget(self.refArrayAdd_pushButton)
        self.refArrayRemove_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.refArrayRemove_pushButton.setObjectName("refArrayRemove_pushButton")
        self.upvRefArray_verticalLayout_2.addWidget(self.refArrayRemove_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.upvRefArray_verticalLayout_2.addItem(spacerItem)
        self.upvRefArray_horizontalLayout.addLayout(self.upvRefArray_verticalLayout_2)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 180, 221, 202))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ctlSize_label = QtWidgets.QLabel(self.layoutWidget)
        self.ctlSize_label.setObjectName("ctlSize_label")
        self.horizontalLayout_3.addWidget(self.ctlSize_label)
        self.ctlSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlSize_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlSize_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlSize_doubleSpinBox.setWrapping(False)
        self.ctlSize_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlSize_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlSize_doubleSpinBox.setMinimum(0.01)
        self.ctlSize_doubleSpinBox.setMaximum(200.0)
        self.ctlSize_doubleSpinBox.setProperty("value", 1.0)
        self.ctlSize_doubleSpinBox.setObjectName("ctlSize_doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.ctlSize_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ctlOffsetScl_label = QtWidgets.QLabel(self.layoutWidget)
        self.ctlOffsetScl_label.setObjectName("ctlOffsetScl_label")
        self.horizontalLayout_6.addWidget(self.ctlOffsetScl_label)
        self.ctlOffsetSclX_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetSclX_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetSclX_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetSclX_doubleSpinBox.setWrapping(False)
        self.ctlOffsetSclX_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetSclX_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetSclX_doubleSpinBox.setMinimum(-360.0)
        self.ctlOffsetSclX_doubleSpinBox.setMaximum(360.0)
        self.ctlOffsetSclX_doubleSpinBox.setSingleStep(1.0)
        self.ctlOffsetSclX_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetSclX_doubleSpinBox.setObjectName("ctlOffsetSclX_doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.ctlOffsetSclX_doubleSpinBox)
        self.ctlOffsetSclY_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetSclY_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetSclY_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetSclY_doubleSpinBox.setWrapping(False)
        self.ctlOffsetSclY_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetSclY_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetSclY_doubleSpinBox.setMinimum(-360.0)
        self.ctlOffsetSclY_doubleSpinBox.setMaximum(360.0)
        self.ctlOffsetSclY_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetSclY_doubleSpinBox.setObjectName("ctlOffsetSclY_doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.ctlOffsetSclY_doubleSpinBox)
        self.ctlOffsetSclZ_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetSclZ_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetSclZ_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetSclZ_doubleSpinBox.setWrapping(False)
        self.ctlOffsetSclZ_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetSclZ_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetSclZ_doubleSpinBox.setMinimum(-360.0)
        self.ctlOffsetSclZ_doubleSpinBox.setMaximum(360.0)
        self.ctlOffsetSclZ_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetSclZ_doubleSpinBox.setObjectName("ctlOffsetSclZ_doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.ctlOffsetSclZ_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ctlOffsetRot_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.ctlOffsetRot_label_2.setObjectName("ctlOffsetRot_label_2")
        self.horizontalLayout_5.addWidget(self.ctlOffsetRot_label_2)
        self.ctlOffsetRotX_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetRotX_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetRotX_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetRotX_doubleSpinBox.setWrapping(False)
        self.ctlOffsetRotX_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetRotX_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetRotX_doubleSpinBox.setMinimum(-360.0)
        self.ctlOffsetRotX_doubleSpinBox.setMaximum(360.0)
        self.ctlOffsetRotX_doubleSpinBox.setSingleStep(1.0)
        self.ctlOffsetRotX_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetRotX_doubleSpinBox.setObjectName("ctlOffsetRotX_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.ctlOffsetRotX_doubleSpinBox)
        self.ctlOffsetRotY_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetRotY_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetRotY_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetRotY_doubleSpinBox.setWrapping(False)
        self.ctlOffsetRotY_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetRotY_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetRotY_doubleSpinBox.setMinimum(-360.0)
        self.ctlOffsetRotY_doubleSpinBox.setMaximum(360.0)
        self.ctlOffsetRotY_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetRotY_doubleSpinBox.setObjectName("ctlOffsetRotY_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.ctlOffsetRotY_doubleSpinBox)
        self.ctlOffsetRotZ_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetRotZ_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetRotZ_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetRotZ_doubleSpinBox.setWrapping(False)
        self.ctlOffsetRotZ_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetRotZ_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetRotZ_doubleSpinBox.setMinimum(-360.0)
        self.ctlOffsetRotZ_doubleSpinBox.setMaximum(360.0)
        self.ctlOffsetRotZ_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetRotZ_doubleSpinBox.setObjectName("ctlOffsetRotZ_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.ctlOffsetRotZ_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ctlOffsetPos_label = QtWidgets.QLabel(self.layoutWidget)
        self.ctlOffsetPos_label.setObjectName("ctlOffsetPos_label")
        self.horizontalLayout_4.addWidget(self.ctlOffsetPos_label)
        self.ctlOffsetPosX_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetPosX_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetPosX_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetPosX_doubleSpinBox.setWrapping(False)
        self.ctlOffsetPosX_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetPosX_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetPosX_doubleSpinBox.setMinimum(-999.0)
        self.ctlOffsetPosX_doubleSpinBox.setMaximum(999.0)
        self.ctlOffsetPosX_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetPosX_doubleSpinBox.setObjectName("ctlOffsetPosX_doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.ctlOffsetPosX_doubleSpinBox)
        self.ctlOffsetPosY_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetPosY_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetPosY_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetPosY_doubleSpinBox.setWrapping(False)
        self.ctlOffsetPosY_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetPosY_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetPosY_doubleSpinBox.setMinimum(-999.0)
        self.ctlOffsetPosY_doubleSpinBox.setMaximum(999.0)
        self.ctlOffsetPosY_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetPosY_doubleSpinBox.setObjectName("ctlOffsetPosY_doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.ctlOffsetPosY_doubleSpinBox)
        self.ctlOffsetPosZ_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlOffsetPosZ_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlOffsetPosZ_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlOffsetPosZ_doubleSpinBox.setWrapping(False)
        self.ctlOffsetPosZ_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlOffsetPosZ_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlOffsetPosZ_doubleSpinBox.setMinimum(-999.0)
        self.ctlOffsetPosZ_doubleSpinBox.setMaximum(999.0)
        self.ctlOffsetPosZ_doubleSpinBox.setProperty("value", 0.0)
        self.ctlOffsetPosZ_doubleSpinBox.setObjectName("ctlOffsetPosZ_doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.ctlOffsetPosZ_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.upvRefArray_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Reference Array", None, -1))
        self.refArrayAdd_pushButton.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.refArrayRemove_pushButton.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))
        self.ctlSize_label.setText(QtWidgets.QApplication.translate("Form", "Ctl Size", None, -1))
        self.ctlOffsetScl_label.setText(QtWidgets.QApplication.translate("Form", "S Offset", None, -1))
        self.ctlOffsetRot_label_2.setText(QtWidgets.QApplication.translate("Form", "R Offset", None, -1))
        self.ctlOffsetPos_label.setText(QtWidgets.QApplication.translate("Form", "T Offset", None, -1))

