"""Structural protocols for Maya/PyMel style dynamic objects."""

from collections.abc import Sequence
from typing import Optional, Protocol, Union, overload


NodeName = str
AttrName = str
PlugPath = str
SpaceName = str
AttrValue = Union[str, int, float, bool, Sequence[float]]


class VectorLike(Protocol):
    x: float
    y: float
    z: float

    @overload
    def __mul__(self, value: float) -> "VectorLike": ...

    @overload
    def __mul__(self, value: "VectorLike") -> float: ...

    def __add__(self, value: "VectorLike") -> "VectorLike": ...
    def __sub__(self, value: "VectorLike") -> "VectorLike": ...
    def __truediv__(self, value: float) -> "VectorLike": ...
    def __imul__(self, value: float) -> "VectorLike": ...
    def __getitem__(self, index: int) -> float: ...
    def length(self) -> float: ...
    def normal(self) -> "VectorLike": ...


class MatrixLike(Protocol):
    def __mul__(self, value: object) -> object: ...
    def __getitem__(self, index: int) -> object: ...
    def inverse(self) -> "MatrixLike": ...


class PlugLike(Protocol):
    def get(self) -> object: ...
    def set(self, value: object) -> None: ...
    def connect(self, other: object, **kwargs: object) -> None: ...
    def disconnect(self) -> None: ...
    def connections(self, **kwargs: object) -> list[object]: ...
    def isLocked(self) -> bool: ...
    def __rshift__(self, other: object) -> object: ...


SettablePlug = PlugLike


class DagNodeLike(Protocol):
    message: object
    match_ref: object

    def __add__(self, value: str) -> str: ...
    def __str__(self) -> str: ...
    def name(self) -> str: ...
    def getName(self) -> str: ...
    def longName(self) -> str: ...
    def hasAttr(self, name: str) -> bool: ...
    def addAttr(self, name: str, **kwargs: object) -> None: ...
    def attr(self, name: str) -> PlugLike: ...
    def setAttr(self, name: str, *values: object, **kwargs: object) -> None: ...
    def getParent(self) -> Optional["DagNodeLike"]: ...
    def getShapes(self) -> list["DagNodeLike"]: ...
    def addChild(self, child: "DagNodeLike", **kwargs: object) -> None: ...


class TransformLike(DagNodeLike, Protocol):
    def getTranslation(self, space: str = "world") -> VectorLike: ...
    def getMatrix(self, **kwargs: object) -> MatrixLike: ...
    def setMatrix(self, matrix: MatrixLike, **kwargs: object) -> None: ...
    def setTransformation(self, matrix: MatrixLike) -> None: ...


class MouseEventLike(Protocol):
    def button(self) -> object: ...
    def ignore(self) -> None: ...


class ComponentLike(Protocol):
    settings: dict[str, object]
    options: dict[str, object]
    groups: dict[str, list[DagNodeLike]]
    transform2Lock: list[DagNodeLike]
    controlers: list[DagNodeLike]
    rig: object
    side: str

    def getName(self, name: str, **kwargs: object) -> str: ...
    def addToGroup(self, node: DagNodeLike, group: str, *args: object) -> None: ...
    def addToSubGroup(self, node: DagNodeLike, group: str) -> None: ...
    def add_controller_tag(self, ctl: DagNodeLike, parent_ctl: Optional[DagNodeLike]) -> None: ...


PymelNode = TransformLike
WorldPoint = Union[Sequence[float], VectorLike]
MatrixValue = Union[MatrixLike, Sequence[float]]
