"""Structural protocols for Maya/PyMel style dynamic objects."""

from collections.abc import Sequence
from typing import Protocol, Union, overload


class VectorLike(Protocol):
    @overload
    def __mul__(self, value: float) -> "VectorLike": ...
    @overload
    def __mul__(self, value: "VectorLike") -> float: ...
    def __add__(self, value: "VectorLike") -> "VectorLike": ...
    def __sub__(self, value: "VectorLike") -> "VectorLike": ...
    def __imul__(self, value: float) -> "VectorLike": ...
    def __getitem__(self, index: int) -> float: ...
    def length(self) -> float: ...
    def normal(self) -> "VectorLike": ...


class SettablePlug(Protocol):
    def set(self, value: float) -> None: ...
    def get(self) -> float: ...


class PymelNode(Protocol):
    message: object
    match_ref: object

    def __add__(self, value: str) -> str: ...
    def name(self) -> str: ...
    def hasAttr(self, name: str) -> bool: ...
    def addAttr(self, name: str, **kwargs: object) -> None: ...
    def attr(self, name: str) -> SettablePlug: ...
    def getParent(self) -> "PymelNode": ...
    def getShapes(self) -> list["PymelNode"]: ...
    def getTranslation(self, space: str) -> VectorLike: ...


WorldPoint = Union[Sequence[float], VectorLike]
